name: Ormsby
favicon: null
layout_spectrum: 0.2451563160866499
typography_spectrum: 0.06665112404152751
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a07'
    - '#45270d'
    - '#424c33'
    - '#9b622b'
    - '#d6aa47'
  brandStrength: 0.5
  lightness: 0.014412832912057638
  saturation: 0.41075514745898545
  rhythmicContrast: 0.13449949910864234
purpose: []
