name: Ormsby
favicon: null
layout_spectrum: 0.50361
typography_spectrum: 0.22112
title: Ormsby
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f63f00'
    - '#5d0200'
    - '#f61800'
    - '#f46c11'
    - '#080000'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
